// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    UpButton: typeof import('./components/up-button.vue')['default']
    UpCard: typeof import('./components/up-card.vue')['default']
    UpCollapse: typeof import('./components/up-collapse.vue')['default']
    UpCollapseItem: typeof import('./components/up-collapse-item.vue')['default']
    UpDialog: typeof import('./components/up-dialog.vue')['default']
    UpForm: typeof import('./components/up-form.vue')['default']
    UpFormItem: typeof import('./components/up-form-item.vue')['default']
    UpIcon: typeof import('./components/up-icon.vue')['default']
    UpImage: typeof import('./components/up-image.vue')['default']
    UpInput: typeof import('./components/up-input.vue')['default']
    UpLink: typeof import('./components/up-link.vue')['default']
    UpOption: typeof import('./components/up-option.vue')['default']
    UpRadio: typeof import('./components/up-radio.vue')['default']
    UpSelect: typeof import('./components/up-select.vue')['default']
  }
}

export { }
